[tool.poetry]
name = "enok-status-checker"
version = "0.1.0"
description = ""
authors = ["Enok contributors"]

[tool.poetry.dependencies]
python = "<4.0,3.8>"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
